### ISSUE TITLE
ResNet-50 crashes

### ISSUE THREAD

**Issue by nickwp** [WatChMaL/WatChMaL#61]
Although ResNet-18 appears to work fine and is what we have usually used by default, when attempting to train with ResNet-50 instead, it crashes with:

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/nprouse/WatChMaL/WatChMaL/main.py", line 132, in main_worker_function
    getattr(engine, task)(task_config)
  File "/home/nprouse/WatChMaL/WatChMaL/watchmal/engine/engine_classifier.py", line 235, in train
    self.validate(val_iter, num_val_batches, checkpointing)
  File "/home/nprouse/WatChMaL/WatChMaL/watchmal/engine/engine_classifier.py", line 307, in validate
    val_res = self.forward(False)
  File "/home/nprouse/WatChMaL/WatChMaL/watchmal/engine/engine_classifier.py", line 157, in forward
    model_out = self.model(data)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 930, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/nprouse/WatChMaL/WatChMaL/watchmal/model/classifier.py", line 18, in forward
    x = self.feature_extractor(x)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/nprouse/WatChMaL/WatChMaL/watchmal/model/resnet.py", line 174, in forward
    x = self.layer1(x)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/nprouse/WatChMaL/WatChMaL/watchmal/model/resnet.py", line 97, in forward
    out += identity
RuntimeError: The size of tensor a (20) must match the size of tensor b (40) at non-singleton dimension 3
```

**Comment by nickwp** [comment]
This might be a bug introduced in #53 when fixing the old buggy ResNet implementation, if only ResNet-18 was fixed but somehow others were not.
